# Truc Vert config file
data_path:
    local_Path: '../../../../data_duck/dems/FRF_geomorphology_DEMs_surveyDEM_19941012.nc'
  #local_Path: '../../FRF_geomorphology_DEMs_surveyDEM_20191025.nc'
    #local_Path: '../../inputdata/bathy/duck_brut/FRF_geomorphology_DEMs_surveyDEM_20000201.nc'

# if you don't use a web link, leave the '' separate by a space else it could be a problem
    web_path: ' '
#    web_path: ' '
    extension: 'nc'
    delimponct: "\t"

    
    missingBathyPath: ' '
    #'http://servdap.legi.grenoble-inp.fr/opendap/meige/19MEPELS/trucvert/Dune_topo_bathy_large_11_2.txt'
    delimPonctMissVal: "\t"

    savePath_preproc: './../../inputdata/bathy/'
    

parameter:
    date_bathy: '1994-10-12'
# size of one side of one grid
    gridsize: 5

    colormaps: 'bwr'

# to calculate the gradient bed elevation
# 0 : no calcul / 1 : calcul
    calGradH: 0

# choice wath you want to save
# 0 : just figures
# 1 : just new bathy data
# 2 : both
    savePlotBathy: 2

interpolation:
# define the method used in the interpolation
# for exemple : 'linear', 'quadratic', 'cubic', 'nearest'
    interpMethod: 'linear'
    
# define the number of subsection on the bathymetry
# the values define the number of subsection on one axis, so the real number is the square of your choice: ex : partition = 2 -> 4 subsection at all
    partition: 2

# you can save the interpolation data of raw bathymetry for an other calculate
# 0 : no save after interpolation / 1 : save after interpolation 
    savehraw: 1

# in case you already done an interpolation with the same parameters before interpolation
# 0 : not using backup / 1 : using backup
    backupInterp: 0

# path to the backup folder interpolation
    folderBackupInterp: './backupInterp/'


z0level:
# mesure systeme of the z = 0 
# zero hydrographique : put "hyd"
# zero zero tide : put "tide"
# zero IGN69 : put "ign"
    zerolevel: "ign"
# in case zerolevel isn't zero hydrographique
# give the difference (absolute) in meter to arrive at zero hydrographique
    difflevel: 2.4


missingValues:
# method to replace missing values into bathymetry
# 0 : no replacement / 1 : replacement with an other bathymetry / 2 : replacement with approximation
    missVal: 0
# if the study area miss more than a value, the bathymetry is automaticaly changed.
# this paramter is involved just if you've choice 1 for missVal
    missmore: 100000
# define the number of subsection on the bathymetry
# the values define the number of subsection on one axis, so the real number is the square of your choice: ex : partition = 2 -> 4 subsection at all
    partition: 2
# define the number of points used to made the approximation
    ptsapprox: 4
# define the method used in the interpolation
# for exemple : 'linear', 'quadratic', 'cubic', 'nearest'
    interpMethod: 'nearest'

changeStudyArea:
# 0: enter the parameters directly in the code
# 1: enter the parameters below
    changeArea: 1
    # point at the sea side
    Xorig: 70
    Yorig: 500 #910
    # cross-shore orientation
    Lx: 520 #870
    # long-shore orientation
    Ly: 1150 #350
    origstudy: 'right'


changeRotation:
# defined the angle between the cross-shore and the north (the angle is the absolute value)
    axisrotation: 180

# if the bathymetry is not straight, to accord the study area "box" with the local landmark
# 0 : inactivated / 1 : activated
    rotArea: 1

# give the rotation sense : to straighten the beach
# 0 : trigo sense / 1 : anti trigo sense
    trigosense: 0.0


# if you want modify the coordinate system of the bathymetry
projection:
# the next 3 parameters are involved before interpolation
# 0 : no transformation / 1 : transformation
    before: 0
# coordinate system bathymetry input
    coorIn_B: "EPSG:4326"
# final coordinate system
    coorOut_B: "EPSG:32119"
# EPSG: 
## 2154 -> lambert93
## 27571 -> lambert1
## 27572 -> lambert2
## 27573 -> lambert3
## 27574 -> lambert4
## 4326 -> WGS
## 32119 -> NAD1983 (duck)
## 4267 -> NAD27 (duck)

# the next 3 parameters are involved after interpolation and replacing values
    after: 0
    coorIn_A: "EPSG:4326"
    coorOut_A: "EPSG:32119"

#coordinate to local coordinate (beach)
    changeCoordGeo: 0



################################################################
# input file for analyse and modif preprocessing mnt
################################################################
data_path_saved:
    inputPath: "./../../inputdata/bathy/nord_duck/duck2019-10-25_nonFilter_bathy.nc"


#############################################################
# analyse_preprocessing_mnt

# conditions meanning on a hard event onto 12h in the years 
storm:
    T12_Y: 17.780657083333335
    H12_Y: 3.7203817166666666
# mean values on some months or also years 
# not mandatory
mean:
    T_mean: 9.245126977938098
    H_mean: 0.8227235608996553

doc:
# choice of the depth of closure formula
# Hallermeier: 0
# Birkemeier: 1
# Houston: 2
# Hallermeier approximated: 3
# see https://apps.dtic.mil/sti/pdfs/ADA578584.pdf for precisions
    formula: 0

# size of the sand grains
sand_size:
    D50: 300e-6
    rhos: 2650

sealevel:
# to define the sea level you've 3 choices: 
# - IGN69: 0
# - Middle-tide: 1
# - zero-hydro: 2
    defined_zero: 2
# if choice different than zero hydrographic please give the 
# diffence heigth between your choice and zero hydro 
# if you don't know the delta between the h zero data and the zero-hydro
# put : 'NaN'
    diff_to_zero_hydro: -0.667
# if you have the elevation for HTL and LTL fill the below variables
# else put : 'NaN'   
    HTL: 0.360
    LTL: -0.623
# approximation with the max height of the bathymetry 0 to 1
    HTL_approx: 'nan'
    tidalrange: 0.983

tide:
# Mean spring tide range
  MSR: 1.2

fit_dissipative:
    sigma: 3
    nbs_fit: 3

# Real waves conditions
waves_data_path:
  input_waves: './forcing_duck_daily_8m_1990-2022.dat'

#############################################################################
# modif_bathy_preproc

sandbar:
    # possibility to create 0 / 1 or 2 bar
    number_of_bar: 2
    outerbar:
        width: 150
        height: 3
        position: 810
          # put 'NaN' if you want just a straight bar
        lambda: NaN
    innerbar:
        width: 50
        height: 0.5
        position: 1190
        lambda: NaN

